version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    networks:
      - base-network
    restart: unless-stopped


networks:
  base-network:
    driver: bridge

